update docs

diff --git a/.github/workflows/pypi-publish.yml b/.github/workflows/pypi-publish.yml
--- a/.github/workflows/pypi-publish.yml
+++ b/.github/workflows/pypi-publish.yml
@@ -55,7 +55,7 @@ jobs:
       #
       # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
       # ALTERNATIVE: exactly, uncomment the following line instead:
-      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}
+      url: https://pypi.org/project/pvw-cli/${{ github.event.release.name }}
 
     steps:
       - name: Retrieve release distributions
@@ -68,3 +68,17 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           packages-dir: dist/
+      - name: Publish to PyPI
+        run: |
+          python -m pip install twine
+          twine upload dist/*
+        env:
+          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
+          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+
+      - name: Verify Secrets
+        run: |
+          if [ -z "${{ secrets.PYPI_USERNAME }}" ] || [ -z "${{ secrets.PYPI_PASSWORD }}" ]; then
+            echo "PyPI credentials are missing. Please define PYPI_USERNAME and PYPI_PASSWORD in repository secrets."
+            exit 1
+          fi
